enhance splitIdentifierByCaseAndSeparators to support non-case-sensitive languages
omissis/go-jsonschema pull request #170
Opened 2023-11-18 09:40 UTC by zrma

This PR includes modifications to the `splitIdentifierByCaseAndSeparators` function to extend its compatibility with non-case-sensitive languages, such as Korean, Chinese, and Japanese, etc.

Key Points:
- Ensured that the existing functionality for case-sensitive languages remains unaffected.
- Added support for languages without case distinction, handling them accurately while preserving the core logic of the function.

However, I encountered some challenges while trying to expand the test suite to cover these additional language scenarios. Due to my limited familiarity with the existing test structure, I wasn't able to confidently add new test cases for these languages. Therefore, while I have implemented the necessary functionality, the corresponding test cases for non-case-sensitive languages are not included in this PR. I would appreciate any assistance or guidance on this front.

Thank you for considering this contribution, and I look forward to any feedback or suggestions for improvement.

2023-12-17 02:40 UTC, omissis commented
hi @zrma , thanks a lot for the contribution! I will try to take a look at it over the xmas/nye holidays and hopefully merge it! 🙏

2024-01-18 00:10 UTC, omissis requested changes
Hi, thanks again for the contribution and for the patience in waiting for the review! 🙏 
The code looks good to me: if you could just push those little naming fixes I added to the PR I can then merge the PR! 🥂
Unfortunately I have no knowledge of non-case-sensitive languages, but if any user who does will find any bug we could fix it when the need arises. ✌️

2024-01-18 00:10 UTC, omissis commented on internal/x/text/cases.go
> +		stateNonCase
```suggestion
		stateNoCase
```

2024-01-18 00:10 UTC, omissis commented on internal/x/text/cases.go
> +			nextState = stateNonCase
```suggestion
			nextState = stateNoCase
```

2024-01-18 00:10 UTC, omissis commented on internal/x/text/cases.go
> +func isNoneCaseSensitiveLetter(r rune) bool {
```suggestion
func isNotCaseSensitiveLetter(r rune) bool {
```

2024-01-18 00:10 UTC, omissis commented on internal/x/text/cases.go
> +		if !unicode.IsLetter(rIdent[0]) || isNoneCaseSensitiveLetter(rIdent[0]) {
```suggestion
		if !unicode.IsLetter(rIdent[0]) || isNotCaseSensitiveLetter(rIdent[0]) {
```

2024-01-18 01:37 UTC, zrma commented
> Hi, thanks again for the contribution and for the patience in waiting for the review! 🙏 The code looks good to me: if you could just push those little naming fixes I added to the PR I can then merge it! 🥂 Unfortunately I have no knowledge of non-case-sensitive languages, but if any user who does will find any bug we could fix it when the need arises. ✌️

I've made the suggested naming changes as per your review. 
Thank you for the valuable feedback and guidance! 😻  The updated commit has been pushed to the PR.

2024-01-18 01:51 UTC, omissis approved these changes
LGTM

2024-01-18 01:51 UTC, merged